childPipelines:
  scmUrls:
    - git@github.com:sagar1312/screwdriver-migration-external-config-test-pipeline#main:child-pipeline-alpha
    - git@github.com:sagar1312/screwdriver-migration-external-config-test-pipeline.git#main:child-pipeline-beta
    - git@github.com:sagar1312/screwdriver-migration-external-config-child-pipeline-apple.git
parameters:
  p1: p1
  p2:
    value: p2
    description: User running build
jobs:
  main:
    image: node:20
    steps:
      - secrets: echo A:$A_SECRET && echo B:$B_SECRET && echo C:$C_SECRET
    requires: [~pr, ~commit]
    secrets:
      - A_SECRET
      - B_SECRET
      - C_SECRET
    parameters:
      p3: p3
